// Generated by Mock
// http://chenrensong.com

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace One.Mock.Model
{

    public class RootObject
    {

        [JsonProperty("Count")]
        public int Count { get; set; }

    }
}
